version: '3.8'

services:
  service:
    build: .
    container_name: file-converter
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/service
    restart: always
    environment:
      - DOCKERIZED=1
    networks:
      - fpa-network

networks:
  fpa-network:
    driver: bridge
